version: "3.3"
services:
  deploying-my-first-nodejs-app-db:
    container_name: deploying-my-first-nodejs-app-mysql-db
    image: mysql:5.7
    restart: always
    command: --sql_mode="NO_ENGINE_SUBSTITUTION"
    environment:
      MYSQL_DATABASE: "deploying_my_first_nodejs_app_db"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - vol-deploying-my-first-nodejs-app-db:/var/lib/mysql
volumes:
  vol-deploying-my-first-nodejs-app-db:
